name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install & upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        python setup.py flake8
    - name: Test with pytest
      run: |
        python setup.py test
    - name: Pull master & Restart systemd service on production environment
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /opt/stonkmaster
          git pull
          pip install .
          sudo /bin/systemctl restart stonkmaster