name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: abatilo/actions-poetry@v2.0.0
    - name: Install with poetry
      run: |
        poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8
    - name: Test with pytest
      run: |
        poetry run pytest