name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.10
        virtualenvs-create: false
    - name: Install dependencies
      run: poetry install
    - name: Lint with flake8
      run: poetry run flake8
    - name: Test with pytest
      run: poetry run pytest