name: publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install & upgrade pip/setuptools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools build
      - name: Lint with flake8
        run: |
          python setup.py flake8
      - name: Test with pytest
        run: |
          python setup.py test
      - name: Build package
        run: |
          python -m build
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}